apiVersion: v1
kind: Service
metadata:
  name: cassandra-server
  labels:
    app: cassandra
spec:
  ports:
    - port: 9160
      name: client
  selector:
    app: cassandra
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
spec:
  selector:
    matchLabels:
      app: cassandra
  serviceName: cassandra-server
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          imagePullPolicy: Always
          image: "cassandra:3.11.11"
          env:
            - name: CASSANDRA_START_RPC
              value: "true"
          resources:
            requests:
              memory: "2Gi"
              cpu: "0.5"
          ports:
            - containerPort: 9160
              name: client
          volumeMounts:
            - name: datadir
              mountPath: /var/lib/cassandra/data
      imagePullSecrets:
        - name: regcred
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
